name: Compliance
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main]
jobs:
  ci:
    uses: belvo-finance/github-actions-workflows/.github/workflows/ci-danger.yml@main
